# Form implementation generated from reading ui file 'Menu_Ekrani.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Menu(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(110, 110, 591, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_ogrekle = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btn_ogrekle.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.btn_ogrekle.sizePolicy().hasHeightForWidth())
        self.btn_ogrekle.setSizePolicy(sizePolicy)
        self.btn_ogrekle.setMaximumSize(QtCore.QSize(800, 100))
        self.btn_ogrekle.setSizeIncrement(QtCore.QSize(10, 20))
        self.btn_ogrekle.setObjectName("btn_ogrekle")
        self.verticalLayout.addWidget(self.btn_ogrekle)
        self.btn_bilgiler = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btn_bilgiler.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.btn_bilgiler.sizePolicy().hasHeightForWidth())
        self.btn_bilgiler.setSizePolicy(sizePolicy)
        self.btn_bilgiler.setMaximumSize(QtCore.QSize(800, 100))
        self.btn_bilgiler.setSizeIncrement(QtCore.QSize(10, 20))
        self.btn_bilgiler.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.btn_bilgiler)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 20, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_ogrekle.setText(_translate("MainWindow", "OGRENCİ EKLE"))
        self.btn_bilgiler.setText(_translate("MainWindow", "OGRENCİ BİLGİLERİ"))
        self.label.setText(_translate("MainWindow", "ÖĞRENCİ İŞLERİ "))
